apiVersion: apps/v1
kind: Deployment
metadata:
  name: sit737-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sit737
  template:
    metadata:
      labels:
        app: sit737
    spec:
      containers:
      - name: sit737-container
        image: sit737-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
