apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: sit737-app
spec:
  selector:
    app: sit737-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
