apiVersion: apps/v1
kind: Deployment
metadata:
  name: sit737-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sit737-app
  template:
    metadata:
      labels:
        app: sit737-app
    spec:
      containers:
      - name: sit737-app
        image: anenaghosh/sit737-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          value: mongodb://admin:password@mongodb:27017/
