# Use an official Node.js runtime as base image
FROM node:20-alpine

# Set the working directory in the container
WORKDIR /usr/src/app/

# Copy package.json and package-lock.json first
COPY package*.json ./
COPY ./index.js /usr/src/app/index.js


# Install dependencies
RUN npm install

# Copy all remaining app source code
COPY . .

# Expose port 
EXPOSE 3000

# Define the command to run your app
CMD [ "npm", "start" ]
