apiVersion: v1
kind: Service
metadata:
  name: sit737-app-service
spec:
  selector:
    app: sit737-app  
  ports:
    - protocol: TCP
      port: 80  # Port on which the service will be exposed
      targetPort: 80  # Port on which the container is listening
  type: LoadBalancer  
